version: 2
updates:
  - package-ecosystem: bundler
    directory: "/cms"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: develop
  - package-ecosystem: npm
    directory: "/astro"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: develop
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: develop

