services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms_database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./cms
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://cms:password@db:5432/cms_production
      CMS_DATABASE_PASSWORD: password
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:80"

volumes:
  db-data:
